AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless AWS SPA

# Parameters:
#   NextDistributionName:
#     Type: String
#     Default: NextBucket
  
  

Resources:
        
  NextBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub ${AWS::StackName}-nextbucketname
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      # LoggingConfiguration:
      #   DestinationBucketName: !Ref NextLoggingBucket
      #   LogFilePrefix: s3-access-logs
      # VersioningConfiguration:
      #   Status: Enabled
      # BucketEncryption:
      #   ServerSideEncryptionConfiguration:
      #   - ServerSideEncryptionByDefault:
      #       SSEAlgorithm: 'AES256'

  NextBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref NextBucket
      PolicyDocument:
        Id: NextBucketPolicy
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt NextOriginAccessIdentity.S3CanonicalUserId
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref NextBucket
                - /*
    

  NextOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: OAI for Next static resources in S3 bucket

  NextDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - Id: NextBucket
          DomainName: !GetAtt NextBucket.RegionalDomainName
          S3OriginConfig:
            OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${NextOriginAccessIdentity}'
        Enabled: true
        DefaultRootObject: index.html
        # - Id: nextAPIGatewayOrigin
        #   DomainName: !Sub '${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com'
        #   OriginPath: '/Prod'
        #   CustomOriginConfig:
        #     HTTPSPort: '443'
        #     OriginProtocolPolicy: https-only
        # Enabled: 'true'
        # Comment: 'Next.js Distribution'
        # HttpVersion: http2
        # DefaultRootObject: ''
        DefaultCacheBehavior:
          TargetOriginId: NextBucket
          ViewerProtocolPolicy: redirect-to-https
          # CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # 
          ForwardedValues:
            QueryString: 'true'
            Cookies:
              Forward: all
              # Forward: none
          Compress: 'true'
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          CachedMethods:
            - GET
            - HEAD
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

    
       

Outputs:
  NextBucket:
    Description: "S3 bucket for Next static resources"
    Value: !GetAtt NextBucket.Arn
  NextDistribution:
    Description: "CloudFront distribution for Next.js"
    Value: !Ref NextDistribution
  CloudFrontDomain:
    Description: "CloudFront Domain Name"
    Value: !GetAtt NextDistribution.DomainName