version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::471112837636:user/aws-sam-cli-managed-personal-account-d-PipelineUser-0c4EBLF4Lx9H"
permissions_provider = "AWS IAM"

[personal-account-dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::471112837636:role/aws-sam-cli-managed-personal--PipelineExecutionRole-w1ceHg3Srqie"
cloudformation_execution_role = "arn:aws:iam::471112837636:role/aws-sam-cli-managed-perso-CloudFormationExecutionRo-LVTGVTJzrPve"
artifacts_bucket = "aws-sam-cli-managed-personal-accou-artifactsbucket-7twnozkcwdt3"
image_repository = ""
region = "us-east-1"

[personal-account-prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::471112837636:role/aws-sam-cli-managed-personal--PipelineExecutionRole-6bLdiwjc2pGP"
cloudformation_execution_role = "arn:aws:iam::471112837636:role/aws-sam-cli-managed-perso-CloudFormationExecutionRo-qldlJZavVENT"
artifacts_bucket = "aws-sam-cli-managed-personal-accou-artifactsbucket-lvukcyulkbfh"
image_repository = ""
region = "us-east-1"
